### PR TITLE
fix #465

### LINKED ISSUE #465: Toggle is broken on the Histogram widget
The "Toggle widget" option, once activated, doesn't collapse the widget as expected. Actually, nothing happens. 

Also, on Safari, the toggle itself of that option, is misaligned. 

Already gave the deets to @piensaenpixel and I'm assigning this to him.

### PR DESCRIPTION
**Pull request by piensaenpixel**
@nobuti could you take a look?

image

Fix - https://github.com/CartoDB/deep-insights.js/issues/465

### CODE REVIEW

**Comment by nobuti** [comment]
collapse

**Comment by nobuti** [comment]
collapse

@xavijam take a look and ping me if you find anything odd, please, I know you have been working on the histogram widget.

File: src/widgets/histogram/content-view.js [hunk 1]
```diff
@@ -49,6 +49,7 @@ module.exports = cdb.core.View.extend({
 
     this._renderMiniChart();
     this._renderMainChart();
+    this._renderAllValues();
```
Comment (xavijam) [inline src/widgets/histogram/content-view.js]: Why do we need to do that?

Comment (xavijam) [inline src/widgets/histogram/content-view.js]: I mean, we used to follow the "show_stats" property in order to render the stats or not.

File: src/widgets/histogram/content-view.js [hunk 2]
```diff
@@ -213,6 +217,18 @@ module.exports = cdb.core.View.extend({
     this.model.bind('change:avg', this._onChangeAvg, this);
   },
 
+  _unbinds: function () {
+    this._dataviewModel.off('change:bins', this._onChangeBins, this);
```
Comment (xavijam) [inline src/widgets/histogram/content-view.js]: I guess it is important when the histogram is rerendered by any option right?

File: src/widgets/histogram/content-view.js (hunk 1 above)
Comment (nobuti) [inline src/widgets/histogram/content-view.js]: But the thing is if collapsed, we don't render the stats. If we uncollapse it, we render it back. But the values are set only on model change. We need to repaint them.

File: src/widgets/histogram/content-view.js (hunk 2 above)
Comment (nobuti) [inline src/widgets/histogram/content-view.js]: Because we are calling `render` when collapsing, this function unbinds events in order to not duplicate bindings. Below `_setupBindings` is called again.

Comment (xavijam) [inline src/widgets/histogram/content-view.js]: :es:

**Comment by xavijam** [comment]
:es:
